// import './globals.scss';
// import type { Metadata } from 'next';
// import Link from 'next/link';
// import LogoutButton from './(auth)/logout/LogoutButton';
// import HamburgerButton from './components/HamburgerButton';
// import Logo from './components/Logo';
// import styles from './page.module.css';

// export const metadata: Metadata = {
//   title: 'NutriVerse',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <nav className={styles.navContainer}>
//           <div className={styles.logoContainer}>
//             <Logo />
//           </div>
//           <nav className={styles.fixedNav}>
//             <div>
//               <div className={styles.divLinks}>
//                 <Link href="/">Home</Link>
//                 <Link href="/recipes">Recipes</Link>
//                 <Link href="/create-recipe">Create Recipe</Link>
//                 <Link href="/myaccount">My Account</Link>
//               </div>
//               <div className={styles.leftLinks}>
//                 <HamburgerButton />
//                 <Link href="/login">Log In</Link>
//                 <Link href="/register">Register</Link>
//                 <Link href="/recipes-admin">Admin</Link>
//                 <LogoutButton />
//               </div>
//             </div>
//           </nav>
//         </nav>
//         <div>{children}</div>
//       </body>
//     </html>
//   );
// }

import './globals.scss';
import { Metadata } from 'next';
import Link from 'next/link';
// import LogoutButton from './(auth)/logout/LogoutButton';
// import HamburgerButtonClient from './components/HamburgerButtonClient';
import Footer from './components/Footer';
import HamburgerButtonClient from './components/HamburgerButtonClient';
import Logo from './components/Logo';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'NutriVerse',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div>
        <body>
          <div>
            <div>
              <nav className={styles.navContainer}>
                <div className={styles.logoContainer}>
                  <Logo />
                </div>
                <nav className={styles.fixedNav}>
                  <div className={styles.divLinks}>
                    {/* <Link href="/">Home</Link> */}
                    <Link href="/recipes">Recipes</Link>
                    <Link href="/create-recipe">Create Recipe</Link>
                    <Link href="/my-account">My Account</Link>
                  </div>
                </nav>{' '}
                <div className={styles.leftLinks}>
                  <div className={styles.hamburgerBtn}>
                    <HamburgerButtonClient />
                  </div>
                </div>
              </nav>
            </div>
          </div>
          <div>{children}</div>
        </body>

        {/* <footer className={styles.footer}>

          <p>&copy; 2023 NutriVerse. All rights reserved.</p>
        </footer> */}
        <div>
          <Footer />
        </div>
      </div>
    </html>
  );
}
