import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import styles from './page.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Food Diary',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div>
            <div className={styles.divLinks}>
              <Link href="/">Home</Link>
              <Link href="/recipes">Recipes</Link>
              <Link href="/myaccount">My Account</Link>
            </div>
            <div className={styles.leftLinks}>
              <Link href="/login">Log In</Link>
              <Link href="/createaccount">Create Account</Link>
            </div>
          </div>
        </nav>
        <div className={styles.backgroundImage}>{children}</div>
      </body>
    </html>
  );
}
