import '../page.module.css';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { getValidSessionByToken } from '../../database/sessions';
import { MyRecipes } from './MyRecipes';

export const metadata = {
  title: 'Admin page',
  description: 'Generated by create next app',
};

export default async function RecipesAdmin({}: Props) {
  // Task: Add redirect to home if user is logged in
  // 1. Checking if the sessionToken cookie exists
  const sessionTokenCookie = cookies().get('sessionToken');
  // 2. Check if the sessionToken cookie is still valid
  const session =
    sessionTokenCookie &&
    (await getValidSessionByToken(sessionTokenCookie.value));

  // 3. If the sessionToken cookie is valid, redirect to home

  if (!session) redirect('/login?returnTo=/recipes-admin');
  // 4. If the sessionToken cookie is invalid or doesn't exist, show the admin page

  // const animals = await getAnimals();

  return <div>{/* <MyRecipes /> */}lalalla</div>;
}
